publish_mode: editorial_workflow

backend:
  name: git-gateway

media_folder: "static/images/uploads"
public_folder: "/uploads"

media_library:
  name: uploadcare
  config:
    publicKey: myspecialdemopublickey

site_url: https://app.netlify.com/sites/optimistic-mahavira-3c1b9b/deploys

display_url: https://app.netlify.com/sites/optimistic-mahavira-3c1b9b/deploys

collections:
  - name: "posts"
    label: "Posts"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Excerpt", name: "excerpt", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "date" }
      - { label: "Body", name: "body", widget: "markdown" }
