publish_mode: editorial_workflow

backend:
  name: git-gateway

media_folder: "static/images/uploads"

media_library:
  name: uploadcare
  config:
    publicKey: myspecialdemopublickey

site_url: https://app.netlify.com/sites/optimistic-mahavira-3c1b9b/deploys

display_url: https://app.netlify.com/sites/optimistic-mahavira-3c1b9b/deploys

collections:
  - name: "jobs"
    label: "My Jobs"
    folder: "jobs"
    create: true
    fields:
      - { label: "title", name: "title", widget: "string" }
      - { label: "location", name: "location", widget: "string" }
      - { label: "description", name: "description", widget: "markdown" }
